---
- name: Playbook to deprovision Package-build-controller
  tags:
    - openshift
    - thoth

  hosts: localhost
  vars:
    OCP_URL: "{{ lookup('env','OCP_URL') }}"
    OCP_TOKEN: "{{ lookup('env','OCP_TOKEN') }}"
    OCP_NAMESPACE: "{{ lookup('env','OCP_NAMESPACE') }}"

  gather_facts: false
  connection: local
  tasks:
    - name: Login to OpenShift using provided token
      shell: >
        oc login {{ OCP_URL }} --insecure-skip-tls-verify=true
        --token {{ OCP_TOKEN }}
      changed_when: false

    - name: Delete Objects
      shell: >
        oc --namespace {{ OCP_NAMESPACE }}
        delete all --selector 'component=package-build-controller'
